const usuarios = [
  {
    id: 1,
    nome: "Chef Marco Bianchi",
    usuario: "chef1",
    email: "chef1@saepchef.com",
    senha: "123456",
    imagem: "chef1.jpg",
    tipo: "chef",
  },
  {
    id: 2,
    nome: "Chef Ana Ferreira",
    usuario: "chef2",
    email: "chef2@saepchef.com",
    senha: "123456",
    imagem: "chef2.jpg",
    tipo: "chef",
  },
  {
    id: 3,
    nome: "Chef Lucas Tanaka",
    usuario: "chef3",
    email: "chef3@saepchef.com",
    senha: "123456",
    imagem: "chef3.jpg",
    tipo: "chef",
  },
  {
    id: 4,
    nome: "Mariana Costa",
    usuario: "usuario1",
    email: "usuario1@gmail.com",
    senha: "123456",
    imagem: "usuario1.jpg",
    tipo: "comum",
  },
  {
    id: 5,
    nome: "Rafael Souza",
    usuario: "usuario2",
    email: "usuario2@gmail.com",
    senha: "123456",
    imagem: "usuario2.jpg",
    tipo: "comum",
  },
  {
    id: 6,
    nome: "Beatriz Lima",
    usuario: "usuario3",
    email: "usuario3@gmail.com",
    senha: "123456",
    imagem: "usuario3.jpg",
    tipo: "comum",
  },
];

const receitasIniciais = [
  {
    id: 1,
    titulo: "Receita 1",
    origem: "Itália",
    chefId: 1,
    imagem: "public/receita1.jpg",
    favoritos: [4, 5],
  },
  {
    id: 2,
    titulo: "Receita 2",
    origem: "Japão",
    chefId: 2,
    imagem: "public/receita2.jpg",
    favoritos: [1, 4, 6],
  },
];
